<a href="https://colab.research.google.com/github/wadhankarsanvi/Machine-Learning-codes-/blob/main/AIML_semester_3(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

scikit learn is open source package where source code is easily available constanty developed and improved and it has a very active community also has state of the art ML algos

Numpy is one of the fundamental packages for computing in python

numpy is used for working with arrays

we use numpy instead of array operation in python

numpy is short of numerical python

array object in numpy is called ndarray
50 timesfaster than python lists

New Section

: numpy fundamental package for scientific computing in python

: contains functionality of multidimensional arrays , mathematical operation like algebra operations and fourier transform, pseudorandom number generators.



*   in skykit learn numpy is fundamental data structure

*   scikit learn takes data in the form of numpy arrays.

*   numpy is a python library


*  provides supporting functions making working with ndarray easier
*   used in data science where resources and speed matter a lot

in pythonn lists that serve the purpose of arryas but are slow to process hece we use numpy for better efficiency.




importing numpy library and finding which version of numpy is being used using np.__version__

In [ ]:
import numpy as np
print(np.__version__)
#np is treated as object for numpy library

2.0.2


converting the list into array using the numpy functions

printing different elements and operations on elements of the given array

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
#single dimension is also
print(arr[0])
print(arr[2]+arr[3])
#jo bracket me diya hai that is just list butwe converted list to array by putting np.array so its converted into an numpy array

1
7


printing specific elements of the array using indexing

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print("2nd element on 1st row: ",arr[0,1])
#first row and second column
print("2nd row and 3rd column: ",arr[1,2])
#2nd row and 3rd column
#3rd row 4th column
print("3rd row and 4th column: ",arr[2,3])
#3rd row exist hi nahi karti so error dikha raha hai
#according to indexing from 0 the first is row and second is column
#0 se row and column chalu hoga isliye 3rd row is written by second indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
2nd row and 3rd column:  8


IndexError: index 2 is out of bounds for axis 0 with size 2

printing type of array using type

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


printing specific elements of the array using slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


using dtype to get the type of elements in the array

In [ ]:
arr = np.array([1,2,3,4])
print(arr.dtype)
#dtype mention kiya to get the data type of elements mentioned inside the array jaise is example me int hai so i aaya next example me string hai toh U aaya for unicode string


int64


In [ ]:
import numpy as np
arr = np.array(['banana','apple','mango'])
print(arr.dtype)

<U6


DATA TYPES IN NUMPY :

i - int
b - boolean
u - unsigned int
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type (void)

In [ ]:
#make a copy, change the original array, and display both arrays:

import numpy as np
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
arr[0] = 17
print(x)
print(arr)

[1 2 3 4 5 6]
[17  2  3  4  5  6]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x= arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


using shape attribute to get the dimesions of the array in the form of (rows , columns)

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)
#shape is used to show the dimension of the array

(3, 4)


using ndim to get the specific type of dimensions in the array

In [ ]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print('shape of array :',arr.shape)
#ndmin se n dimension bana sakte hai jaise in this case it is mentioned 5 so there are 5 values where last one is column

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# 17-07-25

2 dimensional array

In [ ]:
import numpy as np
a = np.array([(1,2,3),(3,4,4)])
print(a)
print(type(a))

[[1 2 3]
 [3 4 4]]
<class 'numpy.ndarray'>


printing different atttributes like type of elemets in array , the dimesion of array , the rows and columns of array

In [ ]:
b = np.array([1,2,3])
print(b)
print(b.dtype)

print(a.ndim)
print(b.ndim)
print(a.shape)
print(b.shape)
#(shape sepcifies first rows and colums of the array)

[1 2 3]
int64
2
1
(2, 3)
(3,)


itemsize returns type of individual element in the array which is 16bits = 2 bytes

ndtype is used to give a specific datatype to the elements in the array

size gives the total number of elements in the array (2rows*3columns) = 6

In [ ]:
a = np.array([(1,2,3),(4,5,6)], dtype = 'int16')
print(a.dtype)
print(a.itemsize)
#get itemsize , in bytes
print(a.size)

int16
2
6


In [ ]:
a = np.array([(1,2,3),(4,5,6)], dtype = 'int32')
print(a.dtype)
print(a.itemsize)
#get itemsize , in bytes(1 bit me 8 bytes hote)
print(a.size)


int32
4
6


multplying size of the array and size of each element in bytes gives the total byte of space taken by the array

In [ ]:
print(a.size*a.itemsize)
print(a.nbytes)
# ek element is of 4bytes and there are 6 elements thus the nbytes gives the size of whole array (4*6)

24
24


arrange gives a specific range of elemnts by taking the starting index,  end index and stepping point

In [ ]:
yay = np.arange(start = 1, stop = 10, step = 2)
#arange is alternative for array but it takes a given range and print the array
print(yay)


[1 3 5 7 9]


In [ ]:
JP = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(JP)
print(JP.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [ ]:
#accessing a specific element
print(JP[1,4])
JP[0,-1]

12


np.int64(7)

giving range of elements using slicing

In [ ]:
print(JP[1,:])
print(JP[:,5])
print(JP[0,1:6:2])#slicing(startindex, endindex,stepsize)


[ 8  9 10 11 12 13 14]
[ 6 13]
[2 4 6]


changing a element from the array using slicing and indexing

In [ ]:
JP[1,6] = 20
print(JP)
JP[:,2] = 5
print(JP)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 20]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 20]]


changing element in both the rows of he same column number using slicing

In [ ]:
JP[:,2] = 1,2
print(JP)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 20]]


creating a 3d matrix with first matrix having element 1,2,3,4 and second element having elements 5,6,7,8 in the first matrix there are 1,2 ekements in the first row and 3,4 in the second row


In [ ]:
#3d array is an array of matrices
q = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# ye ek 3d matrix hai with two matrices, the first matrix is having elements(1,2,3,4) where the first row has elements 1,2  and second matrix has elements(5,6,7,8)
print(q)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


slicing of the 3 dimensional array

In [ ]:
print(q[0,1,1])
#first matrix ke second row ka second column
print(q[:,1,:])

4
[[3 4]
 [7 8]]


In [ ]:
q[:,1,:] = [9,9],[9,9]
#dono matrix ke second row ke saare columns ke value ko change kardiya
print(q)

[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]


In [ ]:
a = np.zeros((2,2))
print(a)
# all 0's matrix, specify shape(in this case two rows and two columns)
print(np.zeros((2,2,3)))
# 3d array with two matrices two rows and three columns

[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#all 1's matrix
print(np.ones((4,2,2), dtype = 'int32'))# a matrices or 4d array with 2 cloumns and two rows all filled with 1


[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


full attribute is used to fill array with the type of element we want to fill with creating a matrix of our choice

In [ ]:
print(np.full((2,2),99,dtype = 'float32'))#full is used to create a matrix of your choice

[[99. 99.]
 [99. 99.]]


making a matrix of element 7

In [ ]:
#full_like is used to reuse the previous matrix
print(np.full_like(q,7))

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


filling the array q with random elements

In [ ]:
#creating random number
print(np.random.rand(2,3))
print(np.random.random_sample(q.shape))#random_sample ko purane kisi matrix ki shape me random elements fill karne ke liye

[[0.75638907 0.39638429 0.41776392]
 [0.28599589 0.67691061 0.36491313]]
[[[0.47225135 0.82213097]
  [0.50382216 0.58815527]]

 [[0.0476927  0.83397388]
  [0.89998137 0.66423354]]]


In [ ]:
print(np.random.randint(7,size = (3,3)))#generates 3*3 matrix of random numbers 0(include) to 7(exclude)
print(np.random.randint(-6,6,size = (2,2))) #generates 2*2 matrix of random numbers -6(include) to 6(exclude)
print(np.random.randint(-6,6,2))#generates 2 random numbers -6(include) to 6(exclude)


[[2 4 5]
 [1 4 0]
 [2 0 1]]
[[ 5 -4]
 [-4 -1]]
[ 5 -1]


creating a identity matrix which is always a square matrix with 7 rows

In [ ]:
# print(np.random.randint(-6,6,2))#generates 2 random numbers -6(include) to 6(exclude)
print(np.identity(7,dtype='int16'))#creates identity matrix(always a square matrix)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


COPYING array

In [ ]:
a = np.array([1,2,3,4])
b =a# a is createa
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3 4]
[100   2   3   4]
[100   2   3   4]


In [ ]:
b = a.copy()
print(a)
b[2] = 90
print(b)

[100   2   3   4]
[100   2  90   4]


performing arithmetic operation on the whole array


In [ ]:
a = np.array([1,2,3,4])
print(a)
a+=2
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[1 2 3 4]
[3 4 5 6]
[5 6 7 8]
[1 2 3 4]
[ 6  8 10 12]
[1.5 2.  2.5 3. ]


In [ ]:
b = np.array([1,0,1,0])
print(a+b)
print(a**2)

[4 4 6 6]
[ 9 16 25 36]


printing the sin value of elements of the array

In [ ]:
print(np.sin(a))


[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


printing the cos value of element of array a

In [ ]:
print(np.cos(a))

[-0.9899925  -0.65364362  0.28366219  0.96017029]


give a element of the following sliced part as one and 2

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


multipying matrix a with b

In [ ]:
kaprint(np.matmul(a,b))
#matrix multiplication: ouput would be 2 by 2 matrix
c = np.identity(3)
np.linalg.det(c)#linear algebra se determinant ko call kiya and determinant nikala

[[6. 6.]
 [6. 6.]]


np.float64(1.0)

STATISTICS

In [ ]:
import numpy as np


In [ ]:

stats = np.array([[5,2,3],[4,5,6]])
stats
print(np.max(stats,axis = 1))# it returns the new array with max values from each row
print(np.max(stats, axis = 0))# it returns the new array with max values from each column
print(np.min(stats))
print(np.sum(stats))
sum(sum(stats))

[5 6]
[5 5 6]
2
25


np.int64(25)